config/routes.rb
Rails.application.routes.draw do
  resources :notifications do
    collection { get :events }
  end
  resources :exchange_rates
  get 'reports/accounts'

  get 'reports/trucks'

  get 'reports/trips'

  get 'reports/drivers'

  get 'reports/turn_boys'

  get 'reports/owners'

  get 'reports/cash'

  get '/reports/accounts/:category' => "reports#category", as: "reports_category"

  get '/dashboard' => "dashboard#index", as: "dashboard"
  get '/diesel_expenses/new' => "expenses#new_diesel_expense", as: "new_diesel_expense"
  get '/diesel_expenses/:id/edit' => "expenses#edit_diesel_expense", as: "edit_diesel_expense"
  get '/diesel_expenses' => "expenses#diesel_expenses", as: "diesel_expenses"
  get '/trips/diesel_expense' => "trips#diesel_expense"

  root to: 'home#index'

  post "/trucks/delete_multiple" => "trucks#delete_multiple", as: "delete_multiple_trucks"
  post "/consignees/delete_multiple" => "consignees#delete_multiple", as: "delete_multiple_consignees"
  post "/cities/delete_multiple" => "cities#delete_multiple", as: "delete_multiple_cities"
  post "/trips/delete_multiple" => "trips#delete_multiple", as: "delete_multiple_trips"
  post "/turn_boys/delete_multiple" => "turn_boys#delete_multiple", as: "delete_multiple_turn_boys"
  post "/truck_owners/delete_multiple" => "truck_owners#delete_multiple", as: "delete_multiple_truck_owners"
  post "/products/delete_multiple" => "products#delete_multiple", as: "delete_multiple_products"
  post "/expenses/delete_multiple" => "expenses#delete_multiple", as: "delete_multiple_expenses"
  post "/expense_categories/delete_multiple" => "expense_categories#delete_multiple", as: "delete_multiple_expense_categories"
  post "/drivers/delete_multiple" => "drivers#delete_multiple", as: "delete_multiple_drivers"
  post "/diesel_companies/delete_multiple" => "diesel_companies#delete_multiple", as: "delete_multiple_diesel_companies"
  post "/users/delete_multiple" => "users#delete_multiple", as: "delete_multiple_users"

  post "/expenses/inline_create" => "expenses#inline_create", as: "inline_create_expenses"

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users, except: [:delete]
  resources :diesel_companies, :attachments, :expenses, :products, :trucks, :turn_boys, :drivers, :truck_owners, :expense_categories, :accounts, :truck_cashes, :cashes, :trips, :consignees, :cities
end

app/models/cash.rb
# == Schema Information
#
# Table name: cashes
#
#  id          :integer          not null, primary key
#  date        :date
#  amount_in   :float
#  amount_out  :float
#  balance     :float
#  closed      :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  lpo         :string
#  description :text
#  account_id  :integer
#

class Cash < ApplicationRecord
	include Reportable
	attr_accessor :total_cash

	belongs_to :account
	acts_as_tenant(:account)

	def self.total
		sum(:amount_in)
	end
end

app/controllers/cashes_controller.rb
class CashesController < ApplicationController
  before_action :set_cash, only: [:show, :edit, :update, :destroy]

  # GET /cashes
  # GET /cashes.json
  def index
    @cashes = Cash.all
    @cash = Cash.new
  end

  # GET /cashes/1
  # GET /cashes/1.json
  def show
  end

  # GET /cashes/new
  def new
    @cash = Cash.new
  end

  # GET /cashes/1/edit
  def edit
  end

  # POST /cashes
  # POST /cashes.json
  def create
    @cash = Cash.new(cash_params)
    @cash.balance = Cash.sum(:amount_in) - Expense.sum(:amount)
    if !cash_params[:date].blank?
      date = Date.strptime cash_params[:date], "%m/%d/%Y"
      @cash.date = date
    end

    respond_to do |format|
      if @cash.save
        format.html { redirect_to cashes_path, notice: 'Cash was successfully added.' }
        format.json { render :show, status: :created, location: @cash }
      else
        format.html { render :new }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cashes/1
  # PATCH/PUT /cashes/1.json
  def update
    respond_to do |format|
      if @cash.update(cash_params)
        @cash.total_cash = Cash.total
        @cash.balance = Cash.sum(:amount_in) - Expense.sum(:amount)
        format.html { redirect_to cashes_path, notice: 'Cash was successfully updated.' }
        format.json { render :show, status: :ok, location: @cash }
      else
        format.html { render :edit }
        format.json { render json: @cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cashes/1
  # DELETE /cashes/1.json
  def destroy
    @cash.destroy
    respond_to do |format|
      format.html { redirect_to cashes_url, notice: 'Cash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cash
      @cash = Cash.find(params[:id])
      @cash.total_cash = Cash.total
      @cash.balance = Cash.sum(:amount_in) - Expense.sum(:amount)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cash_params
      params.require(:cash).permit(:date, :amount_in, :amount_out, :balance, :closed, :lpo, :description)
    end
end

app/helpers/cashes_helper.rb
module CashesHelper
end

app/views/cashes/_form.html.haml
= form_for @cash do |f|
  - if @cash.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cash.errors.count, "error")} prohibited this cash from being saved:"
      %ul
        - @cash.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :amount_in
    = f.text_field :amount_in
  .field
    = f.label :amount_out
    = f.text_field :amount_out
  .field
    = f.label :balance
    = f.text_field :balance
  .field
    = f.label :closed
    = f.check_box :closed
  .actions
    = f.submit 'Save'

app/views/cashes/edit.html.haml
%h1 Editing cash

= render 'form'

= link_to 'Show', @cash
\|
= link_to 'Back', cashes_path

app/views/cashes/index.html.haml
.box.box-kasoko
	.box-header.with-border
		%h3.box-title Cash IN/OUT
		.box-tools.pull-right
			.btn-toolbar{role: "toolbar"}
				/ .btn-group
				/ 	%button.btn.btn-box-tool.dropdown-toggle.btn-default{"data-toggle" => "dropdown"}
				/ 		%i.fa.fa-plus
				/ 		New
				/ 		%i.fa.fa-caret-down
				/ 	%ul.dropdown-menu{:role => "menu"}
				/ 		%li
				/ 			%a{:href => ""}
				/ 				Cash
				.btn-group
					%a#cash-out.btn.btn-box-tool.btn-default
						%i.fa.fa-mail-reply
						Cash OUT
				.btn-group
					%a#cash-in.btn.btn-box-tool.btn-default{href: "#", "data-toggle" => "modal", "data-target" => "#cash_in_modal"}
						%i.fa.fa-mail-forward
						Cash IN
					%a#edit-expense.btn.btn-box-tool.btn-default
						%i.fa.fa-edit
						Edit
					%a#delete-expenses.btn.btn-box-tool.btn-default{href: "#", "data-toggle" => "modal", "data-target" => "#delete_expense_modal"}
						%i.fa.fa-times
						Delete
	/ /.box-header
	.box-body.kasoko-body
		.row
			.col-md-12
				/ start:dynamic data table
				.adv-table
					%table#example.exchange-rate.display.table.table-bordered.table-striped
						%thead
							%tr
								%th.no-sort
									= check_box_tag "toggle_expenses"
								%th Date
								%th LPO
								%th Account
								%th Truck
								%th Entity
								%th Quantity
								%th Price
								%th Total Amount
								/ %th Discount
								%th Description
								%th Balance
						%tbody.expenses_table
							- Expense.all.order(created_at: :desc).each do |expense|
								%tr.gradeX
									%td{style: "width: 15px;"}
										= check_box_tag "expense[expense.id]", expense.id
									%td
										= expense.date
									%td
										= link_to expense.lpo, expense_path(expense)
									%td
										= link_to expense.category.name, expense_category_path(expense.category) if !expense.category.nil?
									%td
										= link_to expense.truck.registration_number, truck_path(expense.truck) if !expense.truck.nil?
									%td
										= expense.entity.name if !expense.entity.nil?
									%td
										= expense.quantity
									%td
										= expense.unit_price
									%td
										= expense.amount
									/ %td
									/   0
									/ %td
									/   = link_to expense.trip.name, trip_path(expense.trip) if !expense.trip.nil?
									%td
										= expense.description
									%td
										= to_currency(Cash.sum(:amount_in) - expense.total_before, unit: "")
	.box-footer.kasoko-footer
		.row
			.col-xs-4
				.info-box{href: "#", "data-toggle" => "modal", "data-target" => "#cash_in_list_modal"}
					%span.info-box-icon.bg-aqua
						%i.fa.fa-money
					.info-box-content
						%span.info-box-text 
							Cash In
							%br
							%small#total-cash
								= to_currency(Cash.sum(:amount_in), unit: "")
			.col-xs-4
				.info-box
					%span.info-box-icon.bg-aqua
						%i.fa.fa-money
					.info-box-content
						%span.info-box-text
							Cash Out
							%br
							%small#total-expense
								= to_currency(Expense.sum(:amount), unit: "")
			.col-xs-4
				.info-box
					%span.info-box-icon.bg-aqua
						%i.fa.fa-money
					.info-box-content
						%span.info-box-text
							Balance
							%br
							%small#cash-balance
								= to_currency((Cash.sum(:amount_in) - Expense.sum(:amount)), unit: "")
#delete_expense_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} &times;
				%h4#myModalLabel.modal-title Delete Expenses
			= form_tag delete_multiple_expenses_path do |f|
				.modal-body
					%label#lbl-msg
					= hidden_field_tag 'delete_expenses'
				.modal-footer
					%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 
						%i.fa.fa-times
						Cancel
					%button.btn.btn-danger{:type => "submit"} 
						%i.fa.fa-trash-o
						Delete
#cash_in_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} &times;
				%h4#myModalLabel.modal-title Cash IN
			= form_for @cash do |f|
				.modal-body
					.form-group
						= f.label :amount_in, "Amount"
						= f.text_field :amount_in, class: "form-control"
					.form-group
						= f.label :lpo
						= f.text_field :lpo, class: "form-control"
					.form-group
						= f.label :date
						= f.text_field :date, class: "form-control datepicker"
					.form-group
						= f.label :description
						= f.text_area :description, class: "form-control"
				.modal-footer
					%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 
						%i.fa.fa-times
						Cancel
					%button.btn.btn-kasoko{:type => "submit"} 
						%i.fa.fa-plus
						Add Cash
#cash_in_list_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			.modal-header
				%button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
					%span{"aria-hidden" => "true"} &times;
				%h4#myModalLabel.modal-title Cash IN
			.modal-body
				.row
					.col-md-12
						/ start:dynamic data table
						.adv-table.table_container
							%table#example.cash_table.display.table.table-bordered.table-striped
								%thead
									%tr
										/ %th.no-sort
										/ 	= check_box_tag "toggle_cashes"
										%th Date
										%th LPO
										%th Amount
										%th Description
								%tbody.cashes_table
									- Cash.all.each do |cash|
										%tr.gradeX
											/ %td{style: "width: 15px;"}
											/ 	= check_box_tag "cash[cash.id]", cash.id
											%td
												= cash.date
											%td.editable.lpo{data: { id: cash.id }}
												= cash.lpo
											%td.editable.amount_in{data: { id: cash.id }}
												= cash.amount_in
											%td.editable.description{data: { id: cash.id }}
												= cash.description
			/ .modal-footer
			/ 	%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 
			/ 		%i.fa.fa-times
			/ 		Cancel
			/ 	%button.btn.btn-kasoko{:type => "submit"} 
			/ 		%i.fa.fa-plus
			/ 		Add Cash

app/views/cashes/new.html.haml
%h1 New cash

= render 'form'

= link_to 'Back', cashes_path

app/views/cashes/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @cash.date
%p
  %b Amount in:
  = @cash.amount_in
%p
  %b Amount out:
  = @cash.amount_out
%p
  %b Balance:
  = @cash.balance
%p
  %b Closed:
  = @cash.closed

= link_to 'Edit', edit_cash_path(@cash)
\|
= link_to 'Back', cashes_path