config/routes.rb
Rails.application.routes.draw do
  resources :notifications do
    collection { get :events }
  end
  resources :exchange_rates
  get 'reports/accounts'

  get 'reports/trucks'

  get 'reports/trips'

  get 'reports/drivers'

  get 'reports/turn_boys'

  get 'reports/owners'

  get 'reports/cash'

  get '/reports/accounts/:category' => "reports#category", as: "reports_category"

  get '/dashboard' => "dashboard#index", as: "dashboard"
  get '/diesel_expenses/new' => "expenses#new_diesel_expense", as: "new_diesel_expense"
  get '/diesel_expenses/:id/edit' => "expenses#edit_diesel_expense", as: "edit_diesel_expense"
  get '/diesel_expenses' => "expenses#diesel_expenses", as: "diesel_expenses"
  get '/trips/diesel_expense' => "trips#diesel_expense"

  root to: 'home#index'

  post "/trucks/delete_multiple" => "trucks#delete_multiple", as: "delete_multiple_trucks"
  post "/consignees/delete_multiple" => "consignees#delete_multiple", as: "delete_multiple_consignees"
  post "/cities/delete_multiple" => "cities#delete_multiple", as: "delete_multiple_cities"
  post "/trips/delete_multiple" => "trips#delete_multiple", as: "delete_multiple_trips"
  post "/turn_boys/delete_multiple" => "turn_boys#delete_multiple", as: "delete_multiple_turn_boys"
  post "/truck_owners/delete_multiple" => "truck_owners#delete_multiple", as: "delete_multiple_truck_owners"
  post "/products/delete_multiple" => "products#delete_multiple", as: "delete_multiple_products"
  post "/expenses/delete_multiple" => "expenses#delete_multiple", as: "delete_multiple_expenses"
  post "/expense_categories/delete_multiple" => "expense_categories#delete_multiple", as: "delete_multiple_expense_categories"
  post "/drivers/delete_multiple" => "drivers#delete_multiple", as: "delete_multiple_drivers"
  post "/diesel_companies/delete_multiple" => "diesel_companies#delete_multiple", as: "delete_multiple_diesel_companies"
  post "/users/delete_multiple" => "users#delete_multiple", as: "delete_multiple_users"

  post "/expenses/inline_create" => "expenses#inline_create", as: "inline_create_expenses"

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users, except: [:delete]
  resources :diesel_companies, :attachments, :expenses, :products, :trucks, :turn_boys, :drivers, :truck_owners, :expense_categories, :accounts, :truck_cashes, :cashes, :trips, :consignees, :cities
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: [:show, :edit, :update, :destroy, :edit_diesel_expense]

  # GET /expenses
  # GET /expenses.json
  def index
    if !params[:category].blank?
      if params[:category] == '0'
        redirect_to "#{new_expense_category_path}?name=Diesel"
      else
        @expenses = Expense.where(expense_category_id: params[:category]).order(created_at: :desc)
      end
    elsif !params[:truck].blank?
      @expenses = Expense.where(truck_id: params[:truck]).order(created_at: :desc)
    else
      @expenses = Expense.all.order(created_at: :desc)
    end
  end

  def diesel_expenses
    @expenses = Expense.where(expense_category_id: ExpenseCategory.find_by(name: "Diesel")).order(created_at: :desc)
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  def new_diesel_expense
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
    if @expense.category.name == "Diesel"
      redirect_to edit_diesel_expense_path(@expense)
    end
  end

  def edit_diesel_expense
  end

  def inline_create
    date = Date.strptime expense_params[:date], "%m/%d/%Y"
    @expense = Expense.new(expense_params)
    if @expense.save
      @expense.date = date
      if params[:expense_category] == "Diesel"
        category = ExpenseCategory.find_by name: params[:expense_category]
        @expense.update(expense_category: category)
        company = DieselCompany.find(params[:diesel_company])
        DieselExpense.create! expense: @expense, diesel_company: company, litres: @expense.quantity
      end
      if @expense.currency == "US Dollar"
        @expense.dollar_amount = @expense.amount / ExchangeRate.first.rate
      end
      if @expense.category.name == "Driver Salary"
        @expense.driver = @expense.truck.driver
        # @expense.amount = @expense.truck.driver_salary
      elsif @expense.category.name == "TurnBoy Salary"
        @expense.turn_boy = @expense.truck.turn_boy
        # @expense.amount = @expense.truck.turn_boy_salary
      end
      @expense.save!
      # cash = Cash.today.first
      # cash.update(amount_out: (cash.amount_out + @expense.amount), balance: (cash.balance - @expense.amount))
      render json: {id: @expense.id, amount: @expense.amount, lpo: @expense.lpo, description: @expense.description, truck: (@expense.truck.nil? ? "" : @expense.truck.name), expense_category: @expense.expense_category.name, unit_price: @expense.unit_price, quantity: @expense.quantity, date: @expense.date, entity: (@expense.entity.blank? ? "" : @expense.entity.name), balance: (Cash.sum(:amount_in) - @expense.total_before), total_expense: Expense.total, currency: @expense.currency}
    else
      render json: {error: "Could not create!"}
    end
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        if !params[:expense_category].blank?
          category = ExpenseCategory.find_by name: params[:expense_category]
          if !category.nil?
            @expense.update(expense_category: category)
            if params[:expense_category] == "Diesel"
              company = DieselCompany.find(params[:diesel_company])
              DieselExpense.create! expense: @expense, diesel_company: company, litres: @expense.quantity
            end
          end
          # cash = Cash.today.first
          # cash.update(amount_out: (cash.amount_out + @expense.amount), balance: (cash.balance - @expense.amount))
        end
        format.html { redirect_to expenses_path, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expenses_path, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_multiple
    deleted = 0
    params[:delete_expenses].split(',').each do |id|
      Expense.find(id).destroy
      deleted = deleted + 1
    end
    redirect_to expenses_path, notice: "You have deleted #{deleted} expenses."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:expense_category_id, :amount, :product_id, :driver_id, :truck_id, :turn_boy_id, :user_id, :description, :lpo, :date, :trip_id, :quantity, :unit_price, :currency)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_diesel_expense.html.haml
= form_for @expense, html: {class: 'kasoko-form'} do |f|
  .box-body.kasoko-body
    .row
      .col-md-12
        - if @expense.errors.any?
          #error_explanation
            %h2= "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
            %ul
              - @expense.errors.full_messages.each do |msg|
                %li= msg
        %input#expense_category{type: 'hidden', name: 'expense_category', value: 'Diesel'}
        - if !@expense.new_record?
          %input#diesel-company{type: 'hidden', value: "#{@expense.diesel_expense.blank? ? '' : @expense.diesel_expense.diesel_company.id}"}
          %input#expense-truck{type: 'hidden', value: "#{@expense.truck.blank? ? '' : @expense.truck.id}"}
        - else
          %input#expense_truck{type: 'hidden', value: params[:truck]}
        .row
          .col-sm-6
            .form-group
              %label Diesel Company
              %select#diesel_company_id.form-control{name: "diesel_company"}
                - DieselCompany.all.each do |company|
                  %option{value: company.id}
                    = company.name
          .col-sm-6
            .form-group
              = f.label :truck
              %select#expense_truck_id.form-control{name: "expense[truck_id]"}
                - Truck.all.each do |truck|
                  %option{value: truck.id}
                    = truck.registration_number
        .row
          .col-sm-6
            .form-group
              %label Litres
              = f.text_field :quantity, class: "form-control"
          .col-sm-6
            .form-group
              %label Price Per Litre
              = f.text_field :unit_price, class: "form-control"
        .row
          .col-sm-6
            .form-group
              = f.label :amount
              = f.text_field :amount, class: "form-control"
          .col-sm-6
            .form-group
              = f.label :lpo, "LPO"
              = f.text_field :lpo, class: "form-control"
        .row          
          .col-sm-12
            .form-group
              = f.label :date
              = f.text_field :date, class: "form-control datepicker"
        .row
          .col-sm-12
            = f.label :description
            = f.text_area :description, class: "form-control"
  .box-footer.kasoko-footer
    .actions.pull-right
      %button.btn.btn-kasoko.btn-rounded{"data-original-title" => "", :title => "", :type => "submit"}
        %i.fa.fa-save
        Save

app/views/expenses/_form.html.haml
= form_for @expense, html: {class: 'kasoko-form'} do |f|
  .box-body.kasoko-body
    .row
      .col-md-12
        - if @expense.errors.any?
          #error_explanation
            %h2= "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
            %ul
              - @expense.errors.full_messages.each do |msg|
                %li= msg
        - if !@expense.new_record?
          %input#expense_category{type: 'hidden', value: "#{@expense.category.blank? ? '' : @expense.category.id}"}
          %input#expense_truck{type: 'hidden', value: "#{@expense.truck.blank? ? '' : @expense.truck.id}"}
          %input#expense_driver{type: 'hidden', value: "#{@expense.driver.blank? ? '' : @expense.driver.id}"}
          %input#expense_turn_boy{type: 'hidden', value: "#{@expense.turn_boy.blank? ? '' : @expense.turn_boy.id}"}
          %input#expense_product{type: 'hidden', value: "#{@expense.product.blank? ? '' : @expense.product.id}"}
        - else
          %input#expense_truck{type: 'hidden', value: params[:truck]}
        .row
          .col-sm-6
            .form-group
              = f.label :expense_category
              %select#expense_category.form-control{name: "expense[expense_category_id]"}
                - ExpenseCategory.where.not(name: "Diesel").each do |expense_category|
                  %option{value: expense_category.id}
                    = expense_category.name
          .col-sm-6
            .form-group
              = f.label :truck
              %select#expense_truck_id.form-control{name: "expense[truck_id]"}
                - Truck.all.each do |truck|
                  %option{value: truck.id}
                    = truck.registration_number
        .row
          .col-sm-6.expense-reason
            .form-group
              = f.label :product, "Spare Parts"
              %select.form-control{name: "expense[product_id]"}
                - Product.where(product_type: "Spare Parts").each do |product|
                  %option{value: product.id}
                    = product.name
          .col-sm-6
            .form-group
              = f.label :lpo, "LPO"
              = f.text_field :lpo, class: "form-control"
          / .col-sm-6
          /   .form-group
          /     = f.label :driver
          /     %select.form-control{name: "expense[driver_id]"}
          /       - Driver.all.each do |driver|
          /         %option{value: driver.id}
          /           = driver.name
        .row
          .col-sm-6
            .form-group
              = f.label :quantity
              = f.text_field :quantity, class: "form-control"
          .col-sm-6
            .form-group
              = f.label :unit_price
              = f.text_field :unit_price, class: "form-control"
        .row
          .col-sm-6
            .form-group
              = f.label :amount
              = f.text_field :amount, class: "form-control"
          .col-sm-6
            .form-group
              = f.label :date
              = f.text_field :date, class: "form-control datepicker"
        /   .col-sm-6
        /     .form-group
        /       = f.label :turn_boy
        /       %select.form-control{name: "expense[turn_boy_id]"}
        /         - TurnBoy.all.each do |turn_boy|
        /           %option{value: turn_boy.id}
        /             = turn_boy.name
        / .row
        /   .col-sm-12
        /     .form-group
        /       = f.label :trip
        /       %select.form-control{name: "expense[trip_id]"}
        /         - Trip.all.each do |trip|
        /           %option{value: trip.id}
        /             = trip.name
          
        .row
          .col-sm-12
            = f.label :description
            = f.text_area :description, class: "form-control"
  .box-footer.kasoko-footer
    .actions.pull-right
      %button.btn.btn-kasoko.btn-rounded{"data-original-title" => "", :title => "", :type => "submit"}
        %i.fa.fa-save
        Save

app/views/expenses/diesel_expenses.html.haml
.box.box-kasoko
  .box-header.with-border
    %h3.box-title Diesel Expenses
    .box-tools.pull-right
      .btn-toolbar{role: "toolbar"}
        .btn-group
          %a#new-diesel-expense.btn.btn-box-tool.btn-default{href: new_diesel_expense_path}
            %i.fa.fa-plus
            New
          %a#edit-expense.btn.btn-box-tool.btn-default
            %i.fa.fa-edit
            Edit
          %a#delete-expenses.btn.btn-box-tool.btn-default{href: "#", "data-toggle" => "modal", "data-target" => "#delete_expense_modal"}
            %i.fa.fa-times
            Delete
  / /.box-header
  .box-body.kasoko-body
    .row
      .col-md-12
        / start:dynamic data table
        .adv-table
          %table#example.exchange-rate.display.table.table-bordered.table-striped
            %thead
              %tr
                %th.no-sort
                  = check_box_tag "toggle_expenses"
                %th Date
                %th LPO
                %th Truck
                %th Company
                %th Litres
                %th Price
                %th Total Amount
                / %th Discount
                %th Currency
                %th Description
            %tbody.expenses_table
              - @expenses.each do |expense|
                %tr.gradeX
                  %td{style: "width: 15px;"}
                    = check_box_tag "expense[expense.id]", expense.id
                  %td
                    = expense.date
                  %td
                    = link_to expense.lpo, expense_path(expense)
                  %td
                    = link_to expense.truck.registration_number, truck_path(expense.truck) if !expense.truck.nil?
                  %td
                    = expense.entity.name if !expense.entity.nil?
                  %td
                    = expense.quantity
                  %td
                    = expense.unit_price
                  %td
                    = expense.amount
                  / %td
                  /   0
                  %td
                    = expense.currency
                  %td
                    = expense.description
  .box-footer.kasoko-footer
    .row
      .col-xs-6
        .info-box{href: "#", "data-toggle" => "modal", "data-target" => "#cash_in_list_modal"}
          %span.info-box-icon.bg-aqua
            %i.fa.fa-flask
          .info-box-content
            %span.info-box-text 
              Litres
              %br
              %small#total-cash
                = @expenses.sum(:quantity)
      .col-xs-6
        .info-box
          %span.info-box-icon.bg-aqua
            %i.fa.fa-money
          .info-box-content
            %span.info-box-text
              Diesel Expense Total
              %br
              %small#total-expense
                = to_currency(@expenses.sum(:amount), unit: "KES ")
  #delete_expense_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
          %h4#myModalLabel.modal-title Delete Diesel Expenses
        = form_tag delete_multiple_expenses_path do |f|
          .modal-body
            %label#lbl-msg
            = hidden_field_tag 'delete_expenses'
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 
              %i.fa.fa-times
              Cancel
            %button.btn.btn-danger{:type => "submit"} 
              %i.fa.fa-trash-o
              Delete

app/views/expenses/edit.html.haml
.box.box-kasoko
	.box-header.with-border
		%h3.box-title Edit Expense
	= render 'form'

app/views/expenses/edit_diesel_expense.html.haml
.box.box-kasoko
	.box-header.with-border
		%h3.box-title Edit Diesel Expense
	= render 'diesel_expense'

app/views/expenses/index.html.haml
.box.box-kasoko
  .box-header.with-border
    %h3.box-title Expenses
    .box-tools.pull-right
      .btn-toolbar{role: "toolbar"}
        .btn-group
          %button.btn.btn-box-tool.dropdown-toggle.btn-default{"data-toggle" => "dropdown"}
            %i.fa.fa-filter
            Filter
            %i.fa.fa-caret-down
          %ul.dropdown-menu{:role => "menu"}
            - ExpenseCategory.all.each do |category|
              %li
                %a{:href => "#{expenses_path}?category=#{category.id}"}
                  = category.name
        .btn-group
          %a#new-expense.btn.btn-box-tool.btn-default{href: new_expense_path}
            %i.fa.fa-plus
            New
          / .btn-group
          /   %button.btn.btn-box-tool.dropdown-toggle{"data-toggle" => "dropdown"}
          /     %i.fa.fa-wrench
          /   %ul.dropdown-menu{:role => "menu"}
          /     %li
          /       %a{:href => "#"} Action
          /     %li
          /       %a{:href => "#"} Another action
          /     %li
          /       %a{:href => "#"} Something else here
          /     %li.divider
          /     %li
          /       %a{:href => "#"} Separated link
          %a#edit-expense.btn.btn-box-tool.btn-default
            %i.fa.fa-edit
            Edit
          %a#delete-expenses.btn.btn-box-tool.btn-default{href: "#", "data-toggle" => "modal", "data-target" => "#delete_expense_modal"}
            %i.fa.fa-times
            Delete
  / /.box-header
  .box-body.kasoko-body
    .row
      .col-md-12
        / start:dynamic data table
        .adv-table
          %table#example.exchange-rate.display.table.table-bordered.table-striped
            %thead
              %tr
                %th.no-sort
                  = check_box_tag "toggle_expenses"
                %th Date
                %th LPO
                %th Account
                %th Truck
                %th Entity
                %th Quantity
                %th Price
                %th Total Amount
                / %th Discount
                %th Description
            %tbody.expenses_table
              - @expenses.each do |expense|
                %tr.gradeX
                  %td{style: "width: 15px;"}
                    = check_box_tag "expense[expense.id]", expense.id
                  %td
                    = expense.date
                  %td
                    = link_to expense.lpo, expense_path(expense)
                  %td
                    = link_to expense.category.name, expense_category_path(expense.category) if !expense.category.nil?
                  %td
                    = link_to expense.truck.registration_number, truck_path(expense.truck) if !expense.truck.nil?
                  %td
                    = expense.entity.name if !expense.entity.nil?
                  %td
                    = expense.quantity
                  %td
                    = expense.unit_price
                  %td
                    = expense.amount
                  / %td
                  /   0
                  / %td
                  /   = link_to expense.trip.name, trip_path(expense.trip) if !expense.trip.nil?
                  %td
                    = expense.description
  #delete_expense_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} &times;
          %h4#myModalLabel.modal-title Delete Expenses
        = form_tag delete_multiple_expenses_path do |f|
          .modal-body
            %label#lbl-msg
            = hidden_field_tag 'delete_expenses'
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 
              %i.fa.fa-times
              Cancel
            %button.btn.btn-danger{:type => "submit"} 
              %i.fa.fa-trash-o
              Delete

app/views/expenses/new.html.haml
.box.box-kasoko
	.box-header.with-border
		%h3.box-title New Expense
	= render 'form'

app/views/expenses/new_diesel_expense.html.haml
.box.box-kasoko
	.box-header.with-border
		%h3.box-title New Diesel Expense
	= render 'diesel_expense'

app/views/expenses/show.html.haml
%p#notice= notice

%p
  %b Expense category:
  = @expense.expense_category
%p
  %b Amount:
  = @expense.amount
%p
  %b Product:
  = @expense.product
%p
  %b Driver:
  = @expense.driver
%p
  %b Truck:
  = @expense.truck
%p
  %b Turn boy:
  = @expense.turn_boy
%p
  %b User:
  = @expense.user
%p
  %b Description:
  = @expense.description
%p
  %b Lpo:
  = @expense.lpo

= link_to 'Edit', edit_expense_path(@expense)
\|
= link_to 'Back', expenses_path