config/routes.rb
Rails.application.routes.draw do
  resources :notifications do
    collection { get :events }
  end
  resources :exchange_rates
  get 'reports/accounts'

  get 'reports/trucks'

  get 'reports/trips'

  get 'reports/drivers'

  get 'reports/turn_boys'

  get 'reports/owners'

  get 'reports/cash'

  get '/reports/accounts/:category' => "reports#category", as: "reports_category"

  get '/dashboard' => "dashboard#index", as: "dashboard"
  get '/diesel_expenses/new' => "expenses#new_diesel_expense", as: "new_diesel_expense"
  get '/diesel_expenses/:id/edit' => "expenses#edit_diesel_expense", as: "edit_diesel_expense"
  get '/diesel_expenses' => "expenses#diesel_expenses", as: "diesel_expenses"
  get '/trips/diesel_expense' => "trips#diesel_expense"

  root to: 'home#index'

  post "/trucks/delete_multiple" => "trucks#delete_multiple", as: "delete_multiple_trucks"
  post "/consignees/delete_multiple" => "consignees#delete_multiple", as: "delete_multiple_consignees"
  post "/cities/delete_multiple" => "cities#delete_multiple", as: "delete_multiple_cities"
  post "/trips/delete_multiple" => "trips#delete_multiple", as: "delete_multiple_trips"
  post "/turn_boys/delete_multiple" => "turn_boys#delete_multiple", as: "delete_multiple_turn_boys"
  post "/truck_owners/delete_multiple" => "truck_owners#delete_multiple", as: "delete_multiple_truck_owners"
  post "/products/delete_multiple" => "products#delete_multiple", as: "delete_multiple_products"
  post "/expenses/delete_multiple" => "expenses#delete_multiple", as: "delete_multiple_expenses"
  post "/expense_categories/delete_multiple" => "expense_categories#delete_multiple", as: "delete_multiple_expense_categories"
  post "/drivers/delete_multiple" => "drivers#delete_multiple", as: "delete_multiple_drivers"
  post "/diesel_companies/delete_multiple" => "diesel_companies#delete_multiple", as: "delete_multiple_diesel_companies"
  post "/users/delete_multiple" => "users#delete_multiple", as: "delete_multiple_users"

  post "/expenses/inline_create" => "expenses#inline_create", as: "inline_create_expenses"

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users, except: [:delete]
  resources :diesel_companies, :attachments, :expenses, :products, :trucks, :turn_boys, :drivers, :truck_owners, :expense_categories, :accounts, :truck_cashes, :cashes, :trips, :consignees, :cities
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_reports, only: [:accounts, :category, :cash, :trips]
  def accounts

  end

  def category
    @category = ExpenseCategory.find(params[:category])
  end

  def trucks
  end

  def trips
  end

  def drivers
  end

  def turn_boys
  end

  def owners
  end

  def cash
  end

  private
    def set_reports
      if !params[:truck].blank?
        @truck_query = "truck_id = #{params[:truck]}"
        @truck_name = Truck.find(params[:truck]).name
        @owner = Truck.find(params[:truck]).owner.name
      end

      if !params[:from].blank? && !params[:to].blank?
        @from = Date.strptime params[:from], "%m/%d/%Y"
        @to = Date.strptime params[:to], "%m/%d/%Y"
      end
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_print_accounts_report.html.haml
%section.content{style: "background: white;"}
	%br
	.row.logo-banner
		= image_tag("logo-banner.png", style: "width: 100%;")
		/ .col-md-2
		/ 	= image_tag("gadano-logo.png", style: "width: 200px;")
		/ .col-md-8
		/ 	.company-name
		/ 		%span#gadano
		/ 			GADANO
		/ 		%span#gen-trade
		/ 			GENERAL TRADING CO. LTD
		/ 	.company-contacts
		/ 		%center
		/ 			%h4
		/ 				HEAD OFFICE
		/ 			%h4
		/ 				JOGOO ROAD PLAZA, THIRD FLOOR, SUITE 8,
		/ 			%h4
		/ 				P.O. BOX 407 - 00507,
		/ 			%h4
		/ 				NAIROBI, KENYA.
		/ 			%h4
		/ 				CELL: +254722145008 / +254721471744
		/ 			%h4
		/ 				EMAIL: info@gadanogeneraltrading.com

		/ .col-md-2
		/ 	= image_tag("gadano-truck.png", style: "width: 200px;")
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: blue"}
					= "Report For #{model_type}"
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: red"}
					- if from.blank? || to.blank?
						- if !truck.blank?
							= "Accounts Statement for #{truck}"
						- else
							= "Accounts Statement"
					- else
						- if truck.blank?
							= "Accounts Statement From #{from} To #{to}"
						- else
							= "Accounts Statement From #{from} To #{to} for #{truck}"
	.row
		.col-md-12
			.table-responsive-has-a-problem-in-this-case
				%table.table
					%thead
						%tr
							%th Date
							%th LPO
							%th Currency
							%th Total Amount
							%th Description
					%tbody
						- expenses.each do |expense|
							%tr
								%td
									= expense.date
								%td
									= expense.lpo
								%td
									= expense.currency || "Kenya Shilling"
								%td
									.pull-right
										= to_currency((expense.is_shilling? ? expense.amount : expense.dollar_amount), unit: "")
								%td
									= expense.description
				%table.table.no-margin{border: 1}
					%tr
						%td
							Dollar Total
						%td
							.pull-right
								= to_currency(expenses.dollar.sum(:dollar_amount), unit: "")
						%td
							Kenya Shilling Total
						%td
							.pull-right
								= to_currency(expenses.shilling.sum(:amount), unit: "")

app/views/reports/_print_cash_report.html.haml
%section.content{style: "background: white;"}
	%br
	.row.logo-banner
		= image_tag("logo-banner.png", style: "width: 100%;")
		/ .col-md-2
		/ 	= image_tag("gadano-logo.png", style: "width: 200px;")
		/ .col-md-8
		/ 	.company-name
		/ 		%span#gadano
		/ 			GADANO
		/ 		%span#gen-trade
		/ 			GENERAL TRADING CO. LTD
		/ 	.company-contacts
		/ 		%center
		/ 			%h4
		/ 				HEAD OFFICE
		/ 			%h4
		/ 				JOGOO ROAD PLAZA, THIRD FLOOR, SUITE 8,
		/ 			%h4
		/ 				P.O. BOX 407 - 00507,
		/ 			%h4
		/ 				NAIROBI, KENYA.
		/ 			%h4
		/ 				CELL: +254722145008 / +254721471744
		/ 			%h4
		/ 				EMAIL: info@gadanogeneraltrading.com

		/ .col-md-2
		/ 	= image_tag("gadano-truck.png", style: "width: 200px;")
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: blue"}
					= "Report For #{model_type}"
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: red"}
					- if from.blank? || to.blank?
						= "Cash Statement"
					- else
						- if truck.blank?
							= "Cash Statement From #{from} To #{to}"
	.row
		.col-md-12
			.table-responsive-has-a-problem-in-this-case
				%table.table
					%thead
						%tr
							%th Date
							%th LPO
							%th Amount
							%th Description
					%tbody
						- Cash.date_between(from, to).each do |cash|
							%tr
								%td
									= cash.created_at.to_date
								%td
									= cash.lpo
								%td
									= cash.amount_in
								%td
									= cash.description
				%table.table.no-margin{border: 1}
					%tr
						%td
							Cash IN 
						%td
							.pull-right
								= to_currency(Cash.date_between(from, to).sum(:amount_in), unit: "")
						/ %td
						/ 	Cash OUT
						/ %td
						/ 	.pull-right
						/ 		= to_currency(expenses.shilling.sum(:amount), unit: "")

app/views/reports/_print_report.html.haml
%section.content{style: "background: white;"}
	%br
	.row.logo-banner
		= image_tag("logo-banner.png", style: "width: 100%;")
		/ .col-md-2
		/ 	= image_tag("gadano-logo.png", style: "width: 200px;")
		/ .col-md-8
		/ 	.company-name
		/ 		%span#gadano
		/ 			GADANO
		/ 		%span#gen-trade
		/ 			GENERAL TRADING CO. LTD
		/ 	.company-contacts
		/ 		%center
		/ 			%h4
		/ 				HEAD OFFICE
		/ 			%h4
		/ 				JOGOO ROAD PLAZA, THIRD FLOOR, SUITE 8,
		/ 			%h4
		/ 				P.O. BOX 407 - 00507,
		/ 			%h4
		/ 				NAIROBI, KENYA.
		/ 			%h4
		/ 				CELL: +254722145008 / +254721471744
		/ 			%h4
		/ 				EMAIL: info@gadanogeneraltrading.com

		/ .col-md-2
		/ 	= image_tag("gadano-truck.png", style: "width: 200px;")
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: blue"}
					= "Accounts Report"
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: red"}
					= "Accounts Statement From #{from} To #{to}"
	.row
		.col-md-12
			.table-responsive
				%table.table
					%thead
						%tr
							%th Date
							%th LPO
							%th Currency
							%th Total Amount
							%th Description
					%tbody
						- expenses.where(@truck_query).date_between(@from, @to).each do |expense|
							%tr
								%td
									= expense.date
								%td
									= expense.lpo
								%td
									= expense.currency || "Kenya Shilling"
								%td
									= to_currency((expense.is_shilling? ? expense.amount : expense.dollar_amount), unit: "")
								%td
									= expense.description
				%table.table.no-margin{border: 1}
					%tr
						%td
							Dollar Total
						%td
							.pull-right
								= to_currency(expenses.dollar.sum(:dollar_amount), unit: "")
						%td
							Kenya Shilling Total
						%td
							.pull-right
								= to_currency(expenses.shilling.sum(:amount), unit: "")

app/views/reports/_print_trips_report.html.haml
%section.content{style: "background: white;"}
	%br
	.row.logo-banner
		= image_tag("logo-banner.png", style: "width: 100%;")
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: blue"}
					- if from.blank? || to.blank?
						- if !truck.blank?
							= "Trip Statement By Truck"
						- else
							= "Trip Statement"
					- else
						- if truck.blank?
							= "Trip Statement By Date Report"
						- else
							= "Trip Statement By Individual Truck & Date Report"
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: red"}
					- if from.blank? || to.blank?
						- if !truck.blank?
							= "Accounts Statement for #{truck}"
						- else
							= "Accounts Statement"
					- else
						- if truck.blank?
							= "Accounts Statement From #{from} To #{to}"
						- else
							= "Statement For #{truck} of #{owner} From #{from} To #{to}"
	.row
		.col-md-12
			.table
				- if !from.blank? || !to.blank?
					- if !truck.blank?
						- truck_expenses[0..-2].each do |record|
							%table.table.dataTable.table-bordered.individual-trips
								%thead
									%tr
										%th{style: "width: 5px;"}
											No.
										%th Date
										%th Depot
										%th Destination
										%th Consignee
										%th Product
										%th Q'Ld
										%th{style: "width: 5px;"}
											Rate
										%th Amount
										%th Comsion
										%th Short
										%th Description
										%th Account
										%th Amt Shs
										%th{style: "width: 5px;"}
											Rate
										%th Amt $
										%th Net Payable
								%tbody#trip-expenses
									%div
										%b
											= "Trip : - (#{truck_expenses.index(record) + 1}. )"
									- record.each do |trip|
										- if !trip[:date].blank?
											%tr.gradeX
												%td
													= trip[:number]
												%td
													= trip[:date]
												%td
													= trip[:depot]
												%td
													= trip[:destination]
												%td
													= trip[:consignee]
												%td
													= trip[:product]
												%td
													.pull-right
														= trip[:quantity]
												%td
													.pull-right
														= trip[:rate]
												%td
													.pull-right
														= trip[:amount]
												%td
													.pull-right
														= trip[:commission]
												%td
													.pull-right
														= trip[:short]
												%td
													= trip[:description]
												%td
													= trip[:account]
												%td
													.pull-right
														= trip[:amount_sh]
												%td
													.pull-right
														= trip[:ex_rate]
												%td
													.pull-right
														= trip[:amount_dol]
												%td
													.pull-right
														= trip[:net_pay]
									%tr
										%td{colspan: 8}
											Total
										%td
											.pull-right
												= record.last[:total_amount]
										%td
											.pull-right
												= record.last[:total_commission]
										%td
											.pull-right
												= record.last[:total_short]
										%td{colspan: 2}
										%td
											.pull-right
												= record.last[:total_shilling]
										%td
										%td
											.pull-right
												= record.last[:total_dollar]
										%td
											.pull-right
												= record.last[:total_net]
						%table.table.dataTable.table-bordered.individual-trips
							%thead
								%tr{style: "background: gray;"}
									%th{style: "width: 5px;"}
									%th
									%th
									%th
									%th
									%th
									%th
									%th{style: "width: 5px;"}
									%th
									%th
									%th
									%th
									%th
									%th
									%th{style: "width: 5px;"}
									%th
									%th
							%tbody#trip-expenses
								%tr.gradeX
									%td{colspan: 8}
										Grand Total
									%td
										.pull-right
											= truck_expenses.last[:grand_amount_total]
									%td
										.pull-right
											= truck_expenses.last[:grand_commission_total]
									%td
										.pull-right
											= truck_expenses.last[:grand_short_total]
									%td{colspan: 2}
									%td
										.pull-right
											= truck_expenses.last[:grand_shilling_total]
									%td
									%td
										.pull-right
											= truck_expenses.last[:grand_dollar_total]
									%td
										.pull-right
											= truck_expenses.last[:grand_net_total]
				- else
					%table.table
						%thead
							%tr
								%th Truck
								%th Driver
								%th Turn boy
								%th Date
								%th Depot
								%th Destination
								%th Consignee
								%th Product
								%th Quantity
								%th Rate
								%th Amount
						%tbody
							- trips.each do |trip|
								%tr.gradeX
									%td
										= trip.truck.registration_number if !trip.truck.blank?
									%td
										= trip.driver.name if !trip.driver.blank?
									%td
										= trip.turn_boy.name if !trip.turn_boy.blank?
									%td
										= trip.date
									%td
										= trip.depot.name if !trip.depot.blank?
									%td
										= trip.destination.name if !trip.destination.blank?
									%td
										= trip.consignee.name if !trip.consignee.blank?
									%td
										= trip.product.name if !trip.product.blank?
									%td
										= trip.quantity
									%td
										= trip.rate
									%td
										.pull-right
											= trip.amount
					%table.table.no-margin{border: 1}
						%tr
							%td
								Total
							%td
								.pull-right
									= to_currency(trips.sum(:amount), unit: "")

app/views/reports/_print_trucks_report.html.haml
%section.content{style: "background: white;"}
	%br
	.row.logo-banner
		= image_tag("logo-banner.png", style: "width: 100%;")
		/ .col-md-2
		/ 	= image_tag("gadano-logo.png", style: "width: 200px;")
		/ .col-md-8
		/ 	.company-name
		/ 		%span#gadano
		/ 			GADANO
		/ 		%span#gen-trade
		/ 			GENERAL TRADING CO. LTD
		/ 	.company-contacts
		/ 		%center
		/ 			%h4
		/ 				HEAD OFFICE
		/ 			%h4
		/ 				JOGOO ROAD PLAZA, THIRD FLOOR, SUITE 8,
		/ 			%h4
		/ 				P.O. BOX 407 - 00507,
		/ 			%h4
		/ 				NAIROBI, KENYA.
		/ 			%h4
		/ 				CELL: +254722145008 / +254721471744
		/ 			%h4
		/ 				EMAIL: info@gadanogeneraltrading.com

		/ .col-md-2
		/ 	= image_tag("gadano-truck.png", style: "width: 200px;")
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: blue"}
					= "Report For #{model_type}"
	.row{style: "border-bottom: 1px solid black;"}
		.col-md-12
			%center
				%h4{style: "color: red"}
					- if from.blank? || to.blank?
						= "Accounts Statement"
					- else
						= "Accounts Statement From #{from} To #{to} for #{truck}"
	.row
		.col-md-12
			.table-responsive-has-a-problem-in-this-case
				%table.table
					%thead
						%tr
							%th Registration Number
							%th Owner
							%th Trips
							%th Expenses
							%th Income
							%th Balance
					%tbody
						- Truck.all.each do |truck|
							%tr
								%td
									= truck.registration_number
								%td
									= truck.owner.name
								%td
									= truck.trips.count
								%td
									= truck.total_expenses
								%td
									= to_currency(truck.income, unit: '')
								%td
									= to_currency(truck.balance, unit: '')
				%table.table.no-margin{border: 1}
					%tr
						%td
							Number of Trucks
						%td
							.pull-right
								= Truck.count

app/views/reports/accounts.html.haml
.box.box-kasoko
	.box-header.with-border
		%h1.box-title
			Reports
			%small Accounts
			%input.truck-selected{type: "hidden", value: params[:truck]}
			%input.from-selected{type: "hidden", value: params[:from]}
			%input.to-selected{type: "hidden", value: params[:to]}
		.box-tools.pull-right
			.btn-toolbar{role: "toolbar"}
				.btn-group
					%select.form-control.filter-by-truck{name: 'truck'}
						%option{value: 0}
							= "-- Filter By Truck --"
						- Truck.all.each do |truck|
							%option{value: truck.id}
								= truck.name
				.btn-group
					%input.form-control.datepicker.from-date{type: "text", placeholder: "From"}
				.btn-group
					%input.form-control.datepicker.to-date{type: "text", placeholder: "To"}
				.btn-group
					%button.btn.btn-kasoko.range-search
						%i.fa.fa-search
				.btn-group
					%button.btn.btn-kasoko.print-report
						%i.fa.fa-print
						Print
	.box-body.kasoko-body
		.row
			.col-md-6
				.info-box
					%span.info-box-icon.bg-aqua
						%i.fa.fa-dollar
					.info-box-content
						%span.info-box-text Dollar Total
						%span.info-box-number
							= to_currency(Expense.dollar.where(@truck_query).date_between(@from, @to).sum(:dollar_amount))
			/ /.col
			.col-md-6
				.info-box
					%span.info-box-icon.bg-red
						%i.fa.fa-money
					.info-box-content
						%span.info-box-text Shilling Total
						%span.info-box-number
							= to_currency(Expense.shilling.where(@truck_query).date_between(@from, @to).sum(:amount), unit: "KES ")
		.box-kasoko
			- ExpenseCategory.all.in_groups_of(2).each do |group|
				.row
					- group.compact.each do |category|
						.col-md-6
							.box.box-kasoko
								.box-header.with-border
									%h3.box-title
										= link_to(category.name, reports_category_path(category))
									.box-tools.pull-right
										%button.btn.btn-box-tool{"data-widget" => "collapse"}
											%i.fa.fa-minus
								.box-body
									.table-responsive
										%table.table.no-margin
											%thead
												%tr
													%th Date
													%th LPO
													%th Currency
													%th Total Amount
													%th Description
											%tbody
												- category.expenses.where(@truck_query).date_between(@from, @to).each do |expense|
													%tr
														%td
															= expense.date
														%td
															= expense.lpo
														%td
															= expense.currency || "Kenya Shilling"
														%td
															= to_currency((expense.is_shilling? ? expense.amount : expense.dollar_amount), unit: "")
														%td
															= expense.description
									/ /.table-responsive
								/ /.box-body
								.box-footer.clearfix
									%a.btn.btn-sm.btn-default.btn-flat
										= "Total Dollar: #{to_currency(category.total_expenses('US Dollar', params[:truck], @from, @to))}"
									%a.btn.btn-sm.btn-default.btn-flat.pull-right
										= "Total Shilling: #{to_currency(category.total_expenses('Kenya Shilling', params[:truck], @from, @to), unit: 'KES ')}"
#print_reports_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			#account-reports
				/ = render 'print_report'
				= render partial: 'print_accounts_report', locals: { model_type: "Accounts", expenses: Expense.where(@truck_query).date_between(@from, @to), from: @from, to: @to, truck: @truck_name }

app/views/reports/drivers.html.haml
%h1 Reports#drivers
%p Find me in app/views/reports/drivers.html.haml

app/views/reports/owners.html.haml
%h1 Reports#owners
%p Find me in app/views/reports/owners.html.haml

app/views/reports/trips.html.haml
.box.box-kasoko
	.box-header.with-border
		%h1.box-title
			Reports
			%small
				Trips
			%input.truck-selected{type: "hidden", value: params[:truck]}
			%input.from-selected{type: "hidden", value: params[:from]}
			%input.to-selected{type: "hidden", value: params[:to]}
		.box-tools.pull-right
			.btn-toolbar{role: "toolbar"}
				.btn-group
					%select.form-control.filter-by-truck{name: 'truck'}
						%option{value: 0}
							= "-- Filter By Truck --"
						- Truck.all.each do |truck|
							%option{value: truck.id}
								= truck.name
				.btn-group
					%input.form-control.datepicker.from-date{type: "text", placeholder: "From"}
				.btn-group
					%input.form-control.datepicker.to-date{type: "text", placeholder: "To"}
				.btn-group
					%button.btn.btn-kasoko.range-search
						%i.fa.fa-search
				.btn-group
					%button.btn.btn-kasoko.print-report
						%i.fa.fa-print
						Print
	.box-body.kasoko-body
		.box.box-default
			.box-body
				.table-responsive
					%table.table.no-margin
						%thead
							%tr
								%th Truck
								%th Driver
								%th Turn boy
								%th Date
								%th Depot
								%th Destination
								%th Consignee
								%th Product
								%th Quantity
								%th Rate
								%th Amount
						%tbody
							- Trip.where(@truck_query).date_between(@from, @to).each do |trip|
								%tr.gradeX
									%td
										= link_to trip.truck.registration_number, truck_path(trip.truck) if !trip.truck.blank?
									%td
										= link_to trip.driver.name, driver_path(trip.driver) if !trip.driver.blank?
									%td
										= link_to trip.turn_boy.name, turn_boy_path(trip.turn_boy) if !trip.turn_boy.blank?
									%td
										= trip.date
									%td
										= link_to trip.depot.name, city_path(trip.depot) if !trip.depot.blank?
									%td
										= link_to trip.destination.name, city_path(trip.destination) if !trip.destination.blank?
									%td
										= link_to trip.consignee.name, consignee_path(trip.consignee) if !trip.consignee.blank?
									%td
										= link_to trip.product.name, product_path(trip.product) if !trip.product.blank?
									%td
										= trip.quantity
									%td
										= trip.rate
									%td
										= trip.amount
#print_reports_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			#account-reports
				= render partial: 'print_trips_report', locals: { owner: @owner, trips: Trip.where(@truck_query).date_between(@from, @to), from: @from, to: @to, truck: @truck_name, truck_expenses: (Truck.find_by(registration_number: @truck_name).nil? ? [] : trip_expenses_table(Truck.find_by(registration_number: @truck_name), @from, @to)) }

app/views/reports/trucks.html.haml
.box.box-kasoko
	.box-header.with-border
		%h1.box-title
			Reports
			%small Trucks
			%input.from-selected{type: "hidden", value: params[:from]}
			%input.to-selected{type: "hidden", value: params[:to]}
		.box-tools.pull-right
			.btn-toolbar{role: "toolbar"}
				.btn-group
					%input.form-control.datepicker.from-date{type: "text", placeholder: "From"}
				.btn-group
					%input.form-control.datepicker.to-date{type: "text", placeholder: "To"}
				.btn-group
					%button.btn.btn-kasoko.range-search
						%i.fa.fa-search
				.btn-group
					%button.btn.btn-kasoko.print-report
						%i.fa.fa-print
						Print
	.box-body.kasoko-body
		/ .row
		/ 	.col-md-4
		/ 		.info-box
		/ 			%span.info-box-icon.bg-aqua
		/ 				%i.fa.fa-truck
		/ 			.info-box-content
		/ 				%span.info-box-text Trucks
		/ 				%span.info-box-number
		/ 					= Truck.count
		.row
			.col-lg-12
				.box.box-default
					.box-body
						.table-responsive
							%table.table.no-margin
								%thead
									%tr
										%th Registration Number
										%th Owner
										%th Trips
										%th Expenses
										%th Income
										%th Balance
								%tbody
									- Truck.all.each do |truck|
										%tr
											%td
												= link_to truck.registration_number, truck_path(truck)
											%td
												= link_to truck.owner.name, truck_owner_path(truck.owner)
											%td
												= link_to truck.trips.count, "#{trips_path}?truck=#{truck.id}"
											%td
												= link_to to_currency(truck.total_expenses, unit: ''), "#{expenses_path}?truck=#{truck.id}"
											%td
												= link_to to_currency(truck.income, unit: ''), "#{trips_path}?truck=#{truck.id}"
											%td
												- if truck.balance > 0
													%span.label.label-success
														= to_currency(truck.balance, unit: '')
												- elsif truck.balance == 0.0
													%span.label.label-primary
														= to_currency(truck.balance, unit: '')
												- else
													%span.label.label-danger
														= "(#{to_currency(truck.balance, unit: '')})"

#print_reports_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
	.modal-dialog
		.modal-content
			#account-reports
				/ = render 'print_report'
				= render partial: 'print_trucks_report', locals: { model_type: "Trucks", from: @from, to: @to, truck: @truck_name }

app/views/reports/turn_boys.html.haml
%h1 Reports#turn_boys
%p Find me in app/views/reports/turn_boys.html.haml