config/routes.rb
Rails.application.routes.draw do
  resources :notifications do
    collection { get :events }
  end
  resources :exchange_rates
  get 'reports/accounts'

  get 'reports/trucks'

  get 'reports/trips'

  get 'reports/drivers'

  get 'reports/turn_boys'

  get 'reports/owners'

  get 'reports/cash'

  get '/reports/accounts/:category' => "reports#category", as: "reports_category"

  get '/dashboard' => "dashboard#index", as: "dashboard"
  get '/diesel_expenses/new' => "expenses#new_diesel_expense", as: "new_diesel_expense"
  get '/diesel_expenses/:id/edit' => "expenses#edit_diesel_expense", as: "edit_diesel_expense"
  get '/diesel_expenses' => "expenses#diesel_expenses", as: "diesel_expenses"
  get '/trips/diesel_expense' => "trips#diesel_expense"

  root to: 'home#index'

  post "/trucks/delete_multiple" => "trucks#delete_multiple", as: "delete_multiple_trucks"
  post "/consignees/delete_multiple" => "consignees#delete_multiple", as: "delete_multiple_consignees"
  post "/cities/delete_multiple" => "cities#delete_multiple", as: "delete_multiple_cities"
  post "/trips/delete_multiple" => "trips#delete_multiple", as: "delete_multiple_trips"
  post "/turn_boys/delete_multiple" => "turn_boys#delete_multiple", as: "delete_multiple_turn_boys"
  post "/truck_owners/delete_multiple" => "truck_owners#delete_multiple", as: "delete_multiple_truck_owners"
  post "/products/delete_multiple" => "products#delete_multiple", as: "delete_multiple_products"
  post "/expenses/delete_multiple" => "expenses#delete_multiple", as: "delete_multiple_expenses"
  post "/expense_categories/delete_multiple" => "expense_categories#delete_multiple", as: "delete_multiple_expense_categories"
  post "/drivers/delete_multiple" => "drivers#delete_multiple", as: "delete_multiple_drivers"
  post "/diesel_companies/delete_multiple" => "diesel_companies#delete_multiple", as: "delete_multiple_diesel_companies"
  post "/users/delete_multiple" => "users#delete_multiple", as: "delete_multiple_users"

  post "/expenses/inline_create" => "expenses#inline_create", as: "inline_create_expenses"

  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :users, except: [:delete]
  resources :diesel_companies, :attachments, :expenses, :products, :trucks, :turn_boys, :drivers, :truck_owners, :expense_categories, :accounts, :truck_cashes, :cashes, :trips, :consignees, :cities
end

app/models/turn_boy.rb
# == Schema Information
#
# Table name: turn_boys
#
#  id           :integer          not null, primary key
#  name         :string
#  phone_number :string
#  address      :string
#  id_number    :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  account_id   :integer
#

class TurnBoy < ApplicationRecord
	attr_accessor :salary
	has_many :truck_turn_boys
	has_many :trucks, through: :truck_turn_boys
	has_many :expenses
	has_many :attachments
	belongs_to :account
	acts_as_tenant(:account)

	def truck
		t = nil
		t = truck_turn_boys.where(active: true).first.truck if !truck_turn_boys.where(active: true).first.nil?
	end

	def calculate_salary truck
		sal = nil
		t = truck_turn_boys.where(truck: truck).first
		sal = t.salary if !t.nil?
	end
end

app/controllers/turn_boys_controller.rb
class TurnBoysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_turn_boy, only: [:show, :edit, :update, :destroy]

  # GET /turn_boys
  # GET /turn_boys.json
  def index
    @turn_boys = TurnBoy.all
  end

  # GET /turn_boys/1
  # GET /turn_boys/1.json
  def show
  end

  # GET /turn_boys/new
  def new
    @turn_boy = TurnBoy.new
  end

  # GET /turn_boys/1/edit
  def edit
  end

  # POST /turn_boys
  # POST /turn_boys.json
  def create
    @turn_boy = TurnBoy.new(turn_boy_params)

    respond_to do |format|
      if @turn_boy.save
        format.html { redirect_to new_turn_boy_path, notice: 'Turn boy was successfully created.' }
        format.json { render :show, status: :created, location: @turn_boy }
      else
        format.html { render :new }
        format.json { render json: @turn_boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turn_boys/1
  # PATCH/PUT /turn_boys/1.json
  def update
    respond_to do |format|
      if @turn_boy.update(turn_boy_params)
        format.html { redirect_to turn_boys_path, notice: 'Turn boy was successfully updated.' }
        format.json { render :show, status: :ok, location: @turn_boy }
      else
        format.html { render :edit }
        format.json { render json: @turn_boy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turn_boys/1
  # DELETE /turn_boys/1.json
  def destroy
    @turn_boy.destroy
    respond_to do |format|
      format.html { redirect_to turn_boys_url, notice: 'Turn boy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_multiple
    deleted = 0
    params[:delete_turn_boys].split(',').each do |id|
      TurnBoy.find(id).destroy
      deleted = deleted + 1
    end
    redirect_to turn_boys_path, notice: "You have deleted #{deleted} turn boys."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn_boy
      @turn_boy = TurnBoy.find(params[:id])
      if !params[:truck].blank?
        truck = Truck.find(params[:truck])
        salary = @turn_boy.calculate_salary(truck)
        if !salary.blank?
          @turn_boy.salary = salary
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turn_boy_params
      params.require(:turn_boy).permit(:name, :phone_number, :address, :id_number)
    end
end

app/helpers/turn_boys_helper.rb
module TurnBoysHelper
end

app/views/turn_boys/_form.html.haml
= form_for @turn_boy, html: {class: 'kasoko-form'} do |f|
  .box-body.kasoko-body
    .row
      .col-md-12
        - if @turn_boy.errors.any?
          #error_explanation
            %h2= "#{pluralize(@turn_boy.errors.count, "error")} prohibited this turn_boy from being saved:"
            %ul
              - @turn_boy.errors.full_messages.each do |msg|
                %li= msg
        .form-group
          = f.label :name
          .input-group
            .input-group-addon
              %i.fa.fa-user
            = f.text_field :name, class: "form-control"
        .form-group
          = f.label :phone_number
          .input-group
            .input-group-addon
              %i.fa.fa-phone
            = f.text_field :phone_number, class: "form-control"
        .form-group
          = f.label :id_number
          .input-group
            .input-group-addon
              %i.fa.fa-credit-card
            = f.text_field :id_number, class: "form-control"
        .form-group
          = f.label :address
          .input-group
            .input-group-addon
              %i.fa.fa-map-marker
            = f.text_field :address, class: "form-control"
  .box-footer.kasoko-footer
    .actions.pull-right
      %button.btn.btn-kasoko.btn-rounded{"data-original-title" => "", :title => "", :type => "submit"}
        %i.fa.fa-save
        Save

app/views/turn_boys/edit.html.haml
.box.box-kasoko
	.box-header.with-border
		%h3.box-title Edit Turn Boy
	= render 'form'

app/views/turn_boys/index.html.haml
.box.box-kasoko
  .box-header.with-border
    %h3.box-title TurnBoys
    .box-tools.pull-right
      .btn-toolbar{role: "toolbar"}
        .btn-group
          %a.btn.btn-box-tool.btn-default{href: new_turn_boy_path}
            %i.fa.fa-plus
            New
          / .btn-group
          /   %button.btn.btn-box-tool.dropdown-toggle{"data-toggle" => "dropdown"}
          /     %i.fa.fa-wrench
          /   %ul.dropdown-menu{:role => "menu"}
          /     %li
          /       %a{:href => "#"} Action
          /     %li
          /       %a{:href => "#"} Another action
          /     %li
          /       %a{:href => "#"} Something else here
          /     %li.divider
          /     %li
          /       %a{:href => "#"} Separated link
          %a#edit-turn_boy.btn.btn-box-tool.btn-default
            %i.fa.fa-edit
            Edit
          %a#delete-turn_boys.btn.btn-box-tool.btn-default{href: "#", "data-toggle" => "modal", "data-target" => "#delete_turn_boy_modal"}
            %i.fa.fa-times
            Delete
  / /.box-header
  .box-body.kasoko-body
    .row
      .col-md-12
        / start:dynamic data table
        .adv-table
          %table#example.exchange-rate.display.table.table-bordered.table-striped
            %thead
              %tr
                %th.no-sort
                  = check_box_tag "toggle_turn_boys"
                %th Name
                %th Phone Number
                %th ID Number
                %th Address
                %th Truck
            %tbody.turn_boys_table
              - @turn_boys.each do |turn_boy|
                %tr.gradeX
                  %td
                    = check_box_tag "turn_boy[turn_boy.id]", turn_boy.id
                  %td
                    = link_to turn_boy.name, turn_boy_path(turn_boy)
                  %td
                    = turn_boy.phone_number
                  %td
                    = turn_boy.id_number
                  %td
                    = turn_boy.address
                  %td
                    = link_to turn_boy.truck.registration_number, truck_path(turn_boy.truck) if !turn_boy.truck.nil?
#delete_turn_boy_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        %h4#myModalLabel.modal-title Delete TurnBoys
      = form_tag delete_multiple_turn_boys_path do |f|
        .modal-body
          %label#lbl-msg
          = hidden_field_tag 'delete_turn_boys'
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} 
            %i.fa.fa-times
            Cancel
          %button.btn.btn-danger{:type => "submit"} 
            %i.fa.fa-trash-o
            Delete

app/views/turn_boys/new.html.haml
.box.box-kasoko
	.box-header.with-border
		%h3.box-title New Turn Boy
	= render 'form'

app/views/turn_boys/show.html.haml
.box.box-kasoko
	.box-header.with-border
		%h3.box-title
			= @turn_boy.name
		.box-tools.pull-right
			.btn-toolbar{role: "toolbar"}
				.btn-group
					.btn-group
						%button.btn.btn-box-tool.dropdown-toggle.btn-default{"data-toggle" => "dropdown"}
							%i.fa.fa-plus
							New
							%i.fa.fa-caret-down
						%ul.dropdown-menu{:role => "menu"}
							%li
								%a{:href => "#{new_trip_path}?turn_boy=#{@turn_boy.id}"} Trip
							%li
								%a{:href => "#{new_expense_path}?turn_boy=#{@turn_boy.id}"} Expense
					/ .btn-group
					/ 	%button.btn.btn-box-tool.dropdown-toggle.btn-default{"data-toggle" => "dropdown"}
					/ 		%i.fa.fa-plus
					/ 		Assign New Driver
					/ 	%ul.dropdown-menu{:role => "menu"}
					/ 		- Driver.all.each do |turn_boy|
					/ 			%li
					/ 				%a{:href => "#"}
					/ 					= turn_boy.name
					%a#upload-docs.btn.btn-box-tool.btn-default{href: "#{new_attachment_path}?owner_id=#{@turn_boy.id}&owner_type=turn_boys"}
						%i.fa.fa-cloud-upload
						Upload
					%a.btn.btn-box-tool.btn-default{href: edit_turn_boy_path(@turn_boy)}
						%i.fa.fa-edit
						Edit
					%a.btn.btn-box-tool.btn-default
						%i.fa.fa-times
						Delete
	.box-body.kasoko-body
		.row
			.col-lg-4
				%i.fa.fa-credit-card
				= @turn_boy.id_number
			.col-lg-4
				%i.fa.fa-phone
				= @turn_boy.phone_number
			.col-lg-4
				%i.fa.fa-truck
				= @turn_boy.truck.name if !@turn_boy.truck.nil?
		.row
			.col-lg-4
				%i.fa.fa-money
				= @turn_boy.calculate_salary(@turn_boy.truck) if !@turn_boy.truck.nil?
			.col-lg-4
				Total income:
				1,200,500
			.col-lg-4
				Trips:
				14
		.row
			.col-lg-12
				.box
					%h3 Documents
					%hr
						%div.slick-list
							- @turn_boy.attachments.each do |attachment|
								.small-box.bg-aqua
									.inner
										= image_tag(attachment.file.url, style: "width: 100%;")
									%a.small-box-footer{:href => attachment_path(attachment)}
										%b
											%i.fa.fa-eye
											View